name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
depend: [DiscordSRV, WorldEdit]
author: Rude Yeti, Incorporated
load: POSTWORLD
description: ${project.description}